name: dl_final
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - hydra-core==1.3
    - hydra-submitit-launcher==1.2.0
    - wandb
    - matplotlib==3.4.2
    - numpy==1.23.5
    - omegaconf==2.1.2
    - tqdm==4.65.0